### ISSUE TITLE
拡張が作動するドメイン名の追加

### ISSUE THREAD

**Issue by tojo17** [rutan/akashi-custom-sound-chrome#3]
Hatena の記事からここにきました、とっても面白い拡張を作っていただきありがとうございます m_m

![image](https://github.com/rutan/akashi-custom-sound-chrome/assets/5460009/d2433dbb-90bf-41f7-bf8f-2ee9a4a80098)
設定を確認したところ、この拡張は `https://atnd.ak4.jp/*` でしか作動しない模様ですが、
弊社の akashi ドメインは `atnd-awj.ak4.jp` となってます。

https://akashi.zendesk.com/hc/ja/articles/115000475854-AKASHI-%E5%85%AC%E9%96%8BAPI-%E4%BB%95%E6%A7%98
こちらの公式ドキュメントにも２パターンの URL が記載されています。

もしよかったら、URL を追加しますか、もしくはユーザーが自分で設定できるようにしていただいたら幸いです！

**Comment by rutan** [comment]
ありがとうございます！
v.1.2.0で追加します！

**Comment by tojo17** [comment]
爆速なご対応ありがとうございます！無事使えるようになりました～
